package interpreter;

public enum TokenType {
	EOF, IDENT, NUM, SKIP, BOOL, IN, FALSE, FOR, IF, ELSE, WHILE, POP, PRINT, PUSH, TOP, FST, SND, LENGTH, PAIR, TRUE, VAR, PLUS, TIMES, DIVIDE, ASSIGN, OPEN_PAR, CLOSED_PAR, STMT_SEP, EXP_SEP, START_BLOCK, END_BLOCK, OR, AND, EQ, LTH, NOT, MINUS, START_LIST, END_LIST, AT
}
